# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171010_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.SmallIntegerField(choices=[(1, 'urgent'), (2, 'etc')]),
        ),
        migrations.AddField(
            model_name='user',
            name='new_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
    ]
