# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171017_1724'),
    ]

    operations = [
    ]
